### PR TITLE
Update to account for change in Get-AzureRmStorageAccountKey cmdlet 

### PR DESCRIPTION
**Pull request by adgroc**
Get-AzureRmStorageAccountKey cmdlet in Azure PS 1.4 changed return to array instead of Key1 and Key2 Updated to take change into account and include backward compat for Azure PS 1.x.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@adgroc__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by jamesweb-ms** [comment]
@adgroc -
This is not a sustainable change going forward as code will ended with version specific hacks everywhere.  Can you instead bump required version to 1.4 and just use values?
https://github.com/Azure/azure-iot-remote-monitoring/blob/master/Common/Deployment/DeploymentLib.ps1#L957

Also could you add back in check for Minor.  Sounds like they are allowing breaking changes for minor builds.
https://github.com/Azure/azure-iot-remote-monitoring/blob/master/Common/Deployment/DeploymentLib.ps1#L970

Thanks,
James

**Comment by adgroc** [comment]
Completely agree about the unsustainable nature of the change. Just bumped the required version to 1.4 and added a check for minor version.

**Comment by jamesweb-ms** [comment]
Great, thanks for the change!

**Pull request merged**
